return {
    _default = "stone",

    stone = {
        items = {
            { id = "minecraft:stone",         label = "Pedra",              default = 512 },
            { id = "minecraft:cobblestone",   label = "Pedregulho",         default = 512 },
            { id = "minecraft:oak_log",       label = "Troncos",            default = 128 },
            { id = "minecraft:oak_planks",    label = "Tabuas",             default = 256 },
            { id = "minecraft:coal_block",    label = "Bloco de Carvao",    default = 48  },
            { id = "minecraft:glass",         label = "Vidro",              default = 128 },
            { id = "minecraft:iron_ingot",    label = "Ferro (lingote)",    default = 96  },
            { id = "minecraft:dirt",          label = "Bloco de Terra",     default = 256 },
            { id = "minecraft:sand",          label = "Bloco de Areia",     default = 256 },
            { id = "minecraft:gravel",        label = "Bloco de Cascalho",  default = 256 },
            { id = "minecraft:torch",         label = "Tocha",              default = 256 },
            { id = "minecraft:chest",         label = "Bau",                default = 24  },
            { id = "minecraft:furnace",       label = "Forno",              default = 12  },
            { id = "minecraft:hopper",        label = "Funil",              default = 12  },
            { id = "minecraft:rail",          label = "Trilho",             default = 128 },
            { id = "minecraft:white_wool",    label = "Bloco de La",        default = 128 },
            { id = "minecraft:book",          label = "Livro",              default = 32  },
            { id = "minecraft:diamond",       label = "Diamante",           default = 8   },
        },
    },

    -- ["stone-2"] = {
    --     parent = "stone",
    --     items = {
    --         -- TODO: preencher com as quantidades do tier 2
    --     },
    -- },

    ["stone-3"] = {
        parent = "stone",
        items = {
            { id = "minecraft:stone",         label = "Pedra",              default = 1536 },
            { id = "minecraft:cobblestone",   label = "Pedregulho",         default = 1536 },
            { id = "minecraft:oak_log",       label = "Troncos",            default = 384  },
            { id = "minecraft:oak_planks",    label = "Tabuas",             default = 768  },
            { id = "minecraft:coal_block",    label = "Bloco de Carvao",    default = 144  },
            { id = "minecraft:glass",         label = "Vidro",              default = 384  },
            { id = "minecraft:iron_ingot",    label = "Ferro (lingote)",    default = 384  },
            { id = "minecraft:dirt",          label = "Bloco de Terra",     default = 512  },
            { id = "minecraft:sand",          label = "Bloco de Areia",     default = 512  },
            { id = "minecraft:gravel",        label = "Bloco de Cascalho",  default = 512  },
            { id = "minecraft:torch",         label = "Tocha",              default = 768  },
            { id = "minecraft:chest",         label = "Bau",                default = 64   },
            { id = "minecraft:furnace",       label = "Forno",              default = 32   },
            { id = "minecraft:hopper",        label = "Funil",              default = 32   },
            { id = "minecraft:rail",          label = "Trilho",             default = 384  },
            { id = "minecraft:white_wool",    label = "Bloco de La",        default = 384  },
            { id = "minecraft:book",          label = "Livro",              default = 96   },
            { id = "minecraft:diamond",       label = "Diamante",           default = 32   },
        },
    },

    copper = {
        items = {
            { id = "minecraft:copper_block",   label = "Bloco de Cobre",          default = 128 },
            { id = "minecraft:iron_block",     label = "Bloco de Ferro",          default = 64  },
            { id = "minecraft:redstone_block", label = "Bloco de Redstone",       default = 48  },
            { id = "minecraft:coal_block",     label = "Bloco de Carvao",         default = 96  },
            { id = "minecraft:lapis_block",    label = "Bloco de Lapis-Lazuli",   default = 48  },
            { id = "minecraft:quartz_block",   label = "Bloco de Quartzo",        default = 48  },
            { id = "minecraft:glass",          label = "Bloco de Vidro",          default = 256 },
            { id = "minecraft:calcite",        label = "Bloco de Calcita",        default = 256 },
            { id = "minecraft:andesite",       label = "Bloco de Andesito",       default = 512 },
            { id = "create:andesite_alloy",    label = "Create: Liga Andesito",   default = 256 },
            { id = "create:shaft",             label = "Create: Eixo",            default = 192 },
            { id = "create:cogwheel",          label = "Create: Engrenagem",      default = 96  },
            { id = "create:large_cogwheel",    label = "Create: Eng. Grande",     default = 48  },
            { id = "create:gearbox",           label = "Create: Caixa Eng.",      default = 24  },
            { id = "create:andesite_casing",   label = "Create: Casing Andesito", default = 24  },
            { id = "minecraft:emerald",        label = "Esmeralda",               default = 32  },
        },
    },

    ["copper-2"] = {
        parent = "copper",
        items = {
            { id = "minecraft:copper_block",   label = "Bloco de Cobre",          default = 192 },
            { id = "minecraft:iron_block",     label = "Bloco de Ferro",          default = 96  },
            { id = "minecraft:redstone_block", label = "Bloco de Redstone",       default = 72  },
            { id = "minecraft:coal_block",     label = "Bloco de Carvao",         default = 128 },
            { id = "minecraft:lapis_block",    label = "Bloco de Lapis-Lazuli",   default = 64  },
            { id = "minecraft:quartz_block",   label = "Bloco de Quartzo",        default = 64  },
            { id = "minecraft:glass",          label = "Bloco de Vidro",          default = 384 },
            { id = "minecraft:calcite",        label = "Bloco de Calcita",        default = 384 },
            { id = "minecraft:andesite",       label = "Bloco de Andesito",       default = 768 },
            { id = "create:andesite_alloy",    label = "Create: Liga Andesito",   default = 384 },
            { id = "create:shaft",             label = "Create: Eixo",            default = 256 },
            { id = "create:cogwheel",          label = "Create: Engrenagem",      default = 128 },
            { id = "create:large_cogwheel",    label = "Create: Eng. Grande",     default = 64  },
            { id = "create:gearbox",           label = "Create: Caixa Eng.",      default = 32  },
            { id = "create:andesite_casing",   label = "Create: Casing Andesito", default = 32  },
            { id = "create:basin",             label = "Create: Bacia",           default = 2   },
            { id = "minecraft:emerald",        label = "Esmeralda",               default = 48  },
        },
    },

    ["copper-3"] = {
        parent = "copper-2",
        items = {
            { id = "minecraft:copper_block",   label = "Bloco de Cobre",          default = 320  },
            { id = "minecraft:iron_block",     label = "Bloco de Ferro",          default = 160  },
            { id = "minecraft:redstone_block", label = "Bloco de Redstone",       default = 128  },
            { id = "minecraft:coal_block",     label = "Bloco de Carvao",         default = 192  },
            { id = "minecraft:lapis_block",    label = "Bloco de Lapis-Lazuli",   default = 96   },
            { id = "minecraft:quartz_block",   label = "Bloco de Quartzo",        default = 96   },
            { id = "minecraft:glass",          label = "Bloco de Vidro",          default = 512  },
            { id = "minecraft:andesite",       label = "Bloco de Andesito",       default = 1024 },
            { id = "minecraft:granite",        label = "Bloco de Granito",        default = 512  },
            { id = "create:andesite_alloy",    label = "Create: Liga Andesito",   default = 512  },
            { id = "create:shaft",             label = "Create: Eixo",            default = 384  },
            { id = "create:cogwheel",          label = "Create: Engrenagem",      default = 192  },
            { id = "create:large_cogwheel",    label = "Create: Eng. Grande",     default = 96   },
            { id = "create:gearbox",           label = "Create: Caixa Eng.",      default = 48   },
            { id = "create:andesite_casing",   label = "Create: Casing Andesito", default = 48   },
            { id = "create:mechanical_press",  label = "Create: Prensa Mecanica", default = 2    },
            { id = "create:basin",             label = "Create: Bacia",           default = 4    },
            { id = "create:mechanical_mixer",  label = "Create: Mist. Mecanico",  default = 2    },
        },
    },

    iron = {
        items = {
            { id = "minecraft:iron_block",            label = "Bloco de Ferro",          default = 192 },
            { id = "minecraft:copper_block",          label = "Bloco de Cobre",          default = 160 },
            { id = "minecraft:redstone_block",        label = "Bloco de Redstone",       default = 128 },
            { id = "minecraft:coal_block",            label = "Bloco de Carvao",         default = 192 },
            { id = "minecraft:gold_block",            label = "Bloco de Ouro",           default = 64  },
            { id = "minecraft:quartz_block",          label = "Bloco de Quartzo",        default = 96  },
            { id = "minecraft:glass",                 label = "Bloco de Vidro",          default = 512 },
            { id = "minecraft:obsidian",              label = "Bloco de Obsidiana",      default = 128 },
            { id = "create:andesite_alloy",           label = "Create: Liga Andesito",   default = 512 },
            { id = "create:shaft",                    label = "Create: Eixo",            default = 512 },
            { id = "create:cogwheel",                 label = "Create: Engrenagem",      default = 256 },
            { id = "create:large_cogwheel",           label = "Create: Eng. Grande",     default = 128 },
            { id = "create:encased_chain_drive",      label = "Create: Chain Drive",     default = 32  },
            { id = "ae2:fluix_crystal",               label = "AE2: Cristal Fluix",      default = 256 },
            { id = "powah:dielectric_paste",          label = "Powah: Dielect. Paste",   default = 512 },
            { id = "forbidden_arcanus:arcane_crystal", label = "FA: Arcane Crystal",     default = 64  },
            { id = "minecraft:diamond",               label = "Diamante",                default = 300 },
        },
    },

    ["iron-2"] = {
        parent = "iron",
        items = {
            { id = "minecraft:iron_block",            label = "Bloco de Ferro",          default = 320 },
            { id = "minecraft:copper_block",          label = "Bloco de Cobre",          default = 256 },
            { id = "minecraft:redstone_block",        label = "Bloco de Redstone",       default = 192 },
            { id = "minecraft:coal_block",            label = "Bloco de Carvao",         default = 256 },
            { id = "minecraft:gold_block",            label = "Bloco de Ouro",           default = 96  },
            { id = "minecraft:quartz_block",          label = "Bloco de Quartzo",        default = 128 },
            { id = "minecraft:glass",                 label = "Bloco de Vidro",          default = 768 },
            { id = "minecraft:obsidian",              label = "Bloco de Obsidiana",      default = 192 },
            { id = "create:andesite_alloy",           label = "Create: Liga Andesito",   default = 768 },
            { id = "create:shaft",                    label = "Create: Eixo",            default = 768 },
            { id = "create:cogwheel",                 label = "Create: Engrenagem",      default = 384 },
            { id = "create:large_cogwheel",           label = "Create: Eng. Grande",     default = 192 },
            { id = "create:encased_chain_drive",      label = "Create: Chain Drive",     default = 48  },
            { id = "ae2:fluix_crystal",               label = "AE2: Cristal Fluix",      default = 384 },
            { id = "ae2:inscriber",                   label = "AE2: Inscriber",          default = 2   },
            { id = "powah:dielectric_paste",           remove = true },
            { id = "powah:dielectric_casing",         label = "Powah: Dielect. Casing",  default = 64  },
            { id = "forbidden_arcanus:arcane_crystal", remove = true },
            { id = "forbidden_arcanus:rune",          label = "FA: Rune",                default = 32  },
            { id = "minecraft:diamond",               label = "Diamante",                default = 400 },
        },
    },

    ["iron-3"] = {
        parent = "iron-2",
        items = {
            { id = "minecraft:iron_block",        label = "Bloco de Ferro",          default = 513  },
            { id = "minecraft:copper_block",      label = "Bloco de Cobre",          default = 384  },
            { id = "minecraft:redstone_block",    label = "Bloco de Redstone",       default = 256  },
            { id = "minecraft:coal_block",        label = "Bloco de Carvao",         default = 320  },
            { id = "minecraft:gold_block",        label = "Bloco de Ouro",           default = 128  },
            { id = "minecraft:quartz_block",      label = "Bloco de Quartzo",        default = 160  },
            { id = "minecraft:glass",             label = "Bloco de Vidro",          default = 1024 },
            { id = "minecraft:obsidian",          label = "Bloco de Obsidiana",      default = 256  },
            { id = "create:andesite_alloy",       label = "Create: Liga Andesito",   default = 1024 },
            { id = "create:shaft",                label = "Create: Eixo",            default = 1024 },
            { id = "create:cogwheel",             label = "Create: Engrenagem",      default = 512  },
            { id = "create:large_cogwheel",       label = "Create: Eng. Grande",     default = 256  },
            { id = "create:encased_chain_drive",  label = "Create: Chain Drive",     default = 64   },
            { id = "create:deployer",             label = "Create: Deployer",        default = 4    },
            { id = "ae2:fluix_crystal",           label = "AE2: Cristal Fluix",      default = 512  },
            { id = "ae2:inscriber",               label = "AE2: Inscriber",          default = 4    },
            { id = "ae2:charger",                 label = "AE2: Charger",            default = 4    },
            { id = "powah:dielectric_casing",     label = "Powah: Dielect. Casing",  default = 96   },
            { id = "forbidden_arcanus:rune",      label = "FA: Rune",                default = 48   },
            { id = "minecraft:diamond",           label = "Diamante",                default = 600  },
        },
    },

    redstone = {
        items = {
            { id = "minecraft:redstone_block",    label = "Bloco de Redstone",       default = 256 },
            { id = "minecraft:iron_block",        label = "Bloco de Ferro",          default = 192 },
            { id = "minecraft:copper_block",      label = "Bloco de Cobre",          default = 160 },
            { id = "minecraft:coal_block",        label = "Bloco de Carvao",         default = 128 },
            { id = "minecraft:lapis_block",       label = "Bloco de Lapis-Lazuli",   default = 64  },
            { id = "minecraft:quartz_block",      label = "Bloco de Quartzo",        default = 128 },
            { id = "minecraft:obsidian",          label = "Bloco de Obsidiana",      default = 192 },
            { id = "minecraft:gold_block",        label = "Bloco de Ouro",           default = 96  },
            { id = "create:andesite_alloy",       label = "Create: Liga Andesito",   default = 512 },
            { id = "create:shaft",                label = "Create: Eixo",            default = 384 },
            { id = "create:cogwheel",             label = "Create: Engrenagem",      default = 192 },
            { id = "create:large_cogwheel",       label = "Create: Eng. Grande",     default = 96  },
            { id = "create:gearbox",              label = "Create: Caixa Eng.",      default = 48  },
            { id = "create:andesite_casing",      label = "Create: Casing Andesito", default = 64  },
            { id = "create:electron_tube",        label = "Create: Tubo Eletronico", default = 96  },
            { id = "create:precision_mechanism",  label = "Create: Prec. Mechanism", default = 16  },
            { id = "ae2:logic_processor",         label = "AE2: Proc. Logico",       default = 16  },
            { id = "powah:energizing_rod_basic",  label = "Powah: Rod Basic",        default = 4   },
            { id = "minecraft:diamond",           label = "Diamante",                default = 800 },
        },
    },

    ["redstone-2"] = {
        parent = "redstone",
        items = {
            { id = "minecraft:redstone_block",   label = "Bloco de Redstone",       default = 512  },
            { id = "minecraft:iron_block",       label = "Bloco de Ferro",          default = 384  },
            { id = "minecraft:copper_block",     label = "Bloco de Cobre",          default = 320  },
            { id = "minecraft:coal_block",       label = "Bloco de Carvao",         default = 256  },
            { id = "minecraft:lapis_block",      label = "Bloco de Lapis-Lazuli",   default = 128  },
            { id = "minecraft:quartz_block",     label = "Bloco de Quartzo",        default = 256  },
            { id = "minecraft:obsidian",         label = "Bloco de Obsidiana",      default = 384  },
            { id = "minecraft:gold_block",       label = "Bloco de Ouro",           default = 192  },
            { id = "create:andesite_alloy",      label = "Create: Liga Andesito",   default = 1024 },
            { id = "create:shaft",               label = "Create: Eixo",            default = 768  },
            { id = "create:cogwheel",            label = "Create: Engrenagem",      default = 384  },
            { id = "create:large_cogwheel",      label = "Create: Eng. Grande",     default = 192  },
            { id = "create:gearbox",             label = "Create: Caixa Eng.",      default = 96   },
            { id = "create:andesite_casing",     label = "Create: Casing Andesito", default = 128  },
            { id = "create:electron_tube",       label = "Create: Tubo Eletronico", default = 192  },
            { id = "create:precision_mechanism", label = "Create: Prec. Mechanism", default = 32   },
            { id = "ae2:logic_processor",        label = "AE2: Proc. Logico",       default = 32   },
            { id = "powah:energizing_rod_basic", label = "Powah: Rod Basic",        default = 8    },
            { id = "minecraft:diamond",          label = "Diamante",                default = 1280 },
        },
    },
}
